version: '3'

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    volumes:
      - /usr/share/elasticsearch/data
    ports:
      - ${ES_PORT}:9200
    environment:
      # There is only one es node.
      discovery.type: "single-node"
      node.name: "es01"
      cluster.name: ${CLUSTER_NAME}
      xpack.security.enabled: "false"
      bootstrap.memory_lock: "true"
      # Max Heap size
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
    deploy:
      resources:
        limits:
          memory: ${MEM_LIMIT}
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    ports:
      - ${KIBANA_PORT}:5601
    environment:
      xpack.security.enabled: "false"
      xpack.security.authc.selector.enabled: "false"
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://es01:9200
      ELASTICSEARCH_REQUESTTIMEOUT: 150000
    deploy:
      resources:
        limits:
          memory: ${MEM_LIMIT}
    networks:
      - elastic
    depends_on:
      - es01

  web:
    build: .
    command: uvicorn app.main:app --reload --host 0.0.0.0
    volumes:
      - .:/code
    ports:
      - 8000:8000
    environment:
      ELASTICSEARCH_HOST: http://es01:9200
    networks:
      - elastic
    depends_on:
      - es01

networks:
  elastic:
    driver: bridge